-- Project generated by script.
-- Date: Seg,18/11/2013-19:27:07
-- Author: rogerio
-- Comments: Entity Description: unidade_a0.
 
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_unsigned.all;
use ieee.std_logic_arith.all;
 
entity unidade_a0 is
	port (a, b, c, d: in std_logic; f: out std_logic);
end unidade_a0;
 
architecture estrutural of unidade_a0 is
  -- Declaration of Components.
 component and2
 	port(x, y: in std_logic; z: out std_logic);
 end component;
 
 component or2
 	port(x, y: in std_logic; z: out std_logic);
 end component;

  -- Signals declaration.
 signal s_a0_o0, s_a1_o0: std_logic;

begin
  -- Commands.
  -- Component instantiation and port mapping.
 a0: and2 port map(x=>a, y=>b, z=>s_a0_o0);
 a1: and2 port map(x=>c, y=>d, z=>s_a1_o0);
 o0: or2 port map(x=>s_a0_o0, y=>s_a1_o0, z=>f);
end estrutural;
