-- Project generated by script.
-- Date: Dom,20/01/2013-11:22:53
-- Author: rogerio
-- Comments: Entity Description: and2.
 
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_unsigned.all;
use ieee.std_logic_arith.all;
 
entity and2 is
	port (x, y: in std_logic; z: out std_logic);
end and2;
 
architecture logic of and2 is
  
  
begin
  -- Commands.
  z<= x and y;
end logic;

