-- Project generated by script.
-- Date: Seg,05/05/2014-11:48:02
-- Author: 
-- Comments: Entity Description: unidade_a2.
 
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_unsigned.all;
use ieee.std_logic_arith.all;
 
entity unidade_a2 is
	port (x, y, z, w: in <<type>>; s: out <<type>>);
end unidade_a2;
 
architecture estrutural of unidade_a2 is
  -- Declaration of Components.
 component <<COMPONENT_NAME>>
 	port(<<ports_in>>: in <<type>>; <<ports_out>>: out <<type>>);
 end component;

  -- Signals declaration.
 signal <<s_sinal_1>>, <<s_sinal_2>>, <<s_sinal_N>>: <<type>> <<length>>;

begin
  -- Commands.
  -- Component instantiation and port mapping.
 <<instance_name>>: <<COMPONENT_NAME>> port map(<<port1>>=><<portX>>, <<port2>>=><<portY>>);
end estrutural;

